title: Kim taebeen
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/ktb658/ktb658.github.io.git" # the base hostname & protocol for your site, e.g. http://example.coms
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: 김태빈
tagline: YMHS student
about-description: 저는 용문고 김태빈입니다 # Add Discription
pic: fall.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: gimt5618@gmail.com # Add your Email address
phone: 010 3060 6177 # Add your Phone number
globe: yongmoon.sen.hs.kr/ # Add your website, do not add http://
github: ktb658 # Add your Github handle
instagram: '08_tb_658' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
